🐜 fix(runner): Fix Pacman failing to install packages on Amazon Linux 2 (#167)
CachyOS v3 fails to run pacman while on Amazon Linux 2... causing issues
with running our hosted version on ECS

Exact errors:
```bash
[root@2b6cbba9d746 /]# sudo pacman -Syu vim
error: failed to initialize alpm library:
(root: /, dbpath: /var/lib/pacman/)
could not find or read directory
```